### ISSUE TITLE
KeyError: 'Unable to open object (bad symbol table node signature)'

### ISSUE THREAD

**Issue by theanuragsrivastava** [iamaaditya/VQA_Demo#17]
Loading image features ...
Traceback (most recent call last):
  File "demo.py", line 117, in <module>
    main()
  File "demo.py", line 95, in main
    image_features = get_image_features(args.image_file_name, CNN_weights_file_name)
  File "demo.py", line 58, in get_image_features
    image_features[0,:] = get_image_model(CNN_weights_file_name).predict(im)[0]
  File "demo.py", line 23, in get_image_model
    image_model = VGG_16(CNN_weights_file_name)
  File "/home/anurag/Desktop/VQA_Demo/models/CNN/VGG.py", line 101, in VGG_16
    load_model_legacy(model, weights_path)
  File "/home/anurag/Desktop/VQA_Demo/models/CNN/VGG.py", line 41, in load_model_legacy
    g = f['layer_{}'.format(k)]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/anurag/.local/lib/python3.6/site-packages/h5py/_hl/group.py", line 167, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open

What should I do to resolve this error? Please help

**Comment by iamaaditya** [comment]
Do a git pull origin master. I have pushed the new weights, that should load.

**Comment by Dishank99** [comment]
Hi, even i had the same error. I did pull from your repo. But i am still getting the error..Please help
